Задание 2
nov-alex/JavaSchool pull request #10
Opened 2024-12-22 19:48 UTC by nov-alex

2024-12-23 17:38 UTC, Liman26 requested changes

2024-12-23 17:38 UTC, Liman26 commented on src/main/java/sbp/school/kafka/deserializer/KeyDeserializer.java
> +            logger.error("Ключ не может быть null");
Почему ключ?

2024-12-23 17:38 UTC, Liman26 commented on src/main/java/sbp/school/kafka/deserializer/KeyDeserializer.java
> +            return null;
Может лучше исключение?

2024-12-23 17:38 UTC, Liman26 commented on src/main/java/sbp/school/kafka/deserializer/KeyDeserializer.java
> +public class KeyDeserializer implements Deserializer<String> {
Сразу не обратил внимание что десериализаор только для ключей. Для String есть готовый, зачем нам кастомный?

2024-12-23 17:38 UTC, Liman26 commented on src/main/java/sbp/school/kafka/service/ConsumerService.java
> +                                logger.info("{}: topic = {}, partition = {}, offset = {}",
Будет очень много логов)

2024-12-23 17:38 UTC, Liman26 commented on src/main/java/sbp/school/kafka/service/ConsumerService.java
> +                consumer.commitAsync(currentOffsets,
Если будет исключение, какое смещение будет зафиксировано?

2024-12-23 18:03 UTC, nov-alex commented on src/main/java/sbp/school/kafka/deserializer/KeyDeserializer.java
> +            return null;
Не работает там исключение как задумывалось.. Если в десериалайзере бросить исключение, то даже если его поймать оберткой try {service.poll()} то оно все равно роняет все. Там надо свой обработчик прерываний делать, так как возвращается коллекция рекордом, а обработка идет какого-то рекорда. Я с прерываниями сразу хотел, потом когда разобрался, ушло на это все вс) Так как быть? Пилить свой обработчик прерывания?

2024-12-23 18:05 UTC, nov-alex commented on src/main/java/sbp/school/kafka/deserializer/KeyDeserializer.java
> +public class KeyDeserializer implements Deserializer<String> {
Ну вот я хотел сделать десер и чтоб если ключ (или valeu) нуль/невалид, то не обрабатывать это сообщение, а только логгировать

2024-12-23 18:10 UTC, nov-alex commented on src/main/java/sbp/school/kafka/service/ConsumerService.java
> +                consumer.commitAsync(currentOffsets,
переделаю

2024-12-27 20:46 UTC, Liman26 commented on src/main/java/sbp/school/kafka/deserializer/KeyDeserializer.java
> +            return null;
На данном этапе нет необходимости писать свой обработчик)

2024-12-27 20:46 UTC, Liman26 approved these changes, later dismissed

2025-01-17 09:10 UTC, nov-alex commented on src/main/java/sbp/school/kafka/deserializer/KeyDeserializer.java
> +            logger.error("Ключ не может быть null");
по логике из жизни, ключ всегда должен быть не null

2025-01-20 03:06 UTC, Liman26 requested changes

2025-01-20 03:06 UTC, Liman26 commented on src/main/java/sbp/school/kafka/deserializer/KeyDeserializer.java
> +            logger.error("Ключ не может быть null");
да, я не обратил внимание что это именно для ключа десериализатор, ок.

2025-01-20 03:06 UTC, Liman26 commented on src/main/java/sbp/school/kafka/service/ConsumerService.java
> +                            for (Map.Entry<TopicPartition, OffsetAndMetadata> offset : offsets.entrySet()) {
Перегруженный метод получился. Лямбду можно вынести в отдельный метод, будет более читабельный код

2025-01-20 03:06 UTC, Liman26 commented on src/main/java/sbp/school/kafka/service/ConsumerService.java
> +            consumer.subscribe(Pattern.compile(topicRegExp), new ConsumerRebalanceListener() {
Реализацию слушателя тоже можно вынести в отдельный метод - легче тестировать/сопровождать

2025-01-21 05:32 UTC, nov-alex commented
За несколько коммитов можно не переживать, при заливке делаю rebase и squash

2025-01-23 02:06 UTC, Liman26 approved these changes

2025-01-23 08:20 UTC, merged