Задание 1
nov-alex/JavaSchool pull request #9
Opened 2024-12-21 15:55 UTC by nov-alex

2024-12-23 17:27 UTC, Liman26 requested changes

2024-12-23 17:27 UTC, Liman26 commented on src/main/java/sbp/school/kafka/Task1.java
> +            try (KafkaProducer<String, TransactionData> producer = new KafkaProducer<>(ProducerConfiguration.getProducerConfig())) {
Создай сервис под продюсер, а тестовый/отладочный запуск перенеси в тесты

2024-12-23 17:27 UTC, Liman26 commented on src/main/java/sbp/school/kafka/Task1.java
> +            System.out.println(e.getMessage());
Давай подключим логгер

2024-12-23 17:27 UTC, Liman26 commented on src/main/java/sbp/school/kafka/Task1.java
> +        data.add(new TransactionData(UUID.randomUUID(),
Все тестовые данные, генерацию - в тесты

2024-12-23 17:27 UTC, Liman26 commented on src/main/java/sbp/school/kafka/serializer/TransactionDataSerializer.java
> +        return null;
Потенциальный NPE, лучше пустой массив возвращать или подбрасывать исключение

2024-12-23 17:27 UTC, Liman26 commented on src/main/java/sbp/school/kafka/service/ProducerService.java
> +                            logger.info("Успешная доставка в кафку: Topic {}, Partition {}, Offset {}",
При успешных отправках будет большая нагрузка на логгер, можно debug или trace

2024-12-27 20:47 UTC, Liman26 approved these changes, later dismissed

2025-01-16 03:31 UTC, nov-alex commented on src/main/java/sbp/school/kafka/serializer/TransactionDataSerializer.java
> +        return null;
Я сделал как работает штатный сериалайзер, так как это валидный кейс выходит.

2025-01-20 02:48 UTC, Liman26 approved these changes

2025-01-20 02:48 UTC, Liman26 commented on src/main/java/sbp/school/kafka/entity/TransactionData.java
> +package sbp.school.kafka.entity;
Это скорее DTO, не entity.

2025-01-20 02:52 UTC, Liman26 approved these changes
Доработки по замечаниям надо добавлять в уже существующий коммит, иначе у вас один функционал разными коммитами будет представлен, а по отдельности коммиты будут содержать неполный или нерабочий функционал

2025-01-20 15:59 UTC, merged